#!/bin/sh

if [ -f "$HOME/.profile" ]; then
    . "$HOME/.profile"
fi

set -euf

# Commands. To add new command define variable here, and add variable name to
# cycle below. Command will be run through `eval`.
wpa_gui='/usr/sbin/wpa_gui'
trayer='/usr/bin/trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x191970 --height 12'
if [ -r ~/.fehbg ]; then
    feh="$(cat ~/.fehbg)"
else
    feh='xsetroot -grey'
fi

# Run commands.
for cmd in wpa_gui; do
    # Result will be empty, if either cmd or $cmd is unset or empty.
    eval "set -- ${cmd:+\${$cmd:+\$$cmd\}}"; 
    if which "${1:-}" >/dev/null ; then
	echo "Run $cmd"
	# I need `eval` for compatibility with ~/.fehbg format.
	eval "$@" &
    else
	echo "Can't run $cmd."
    fi
done

user_session_lib_dir="$HOME/.Xsession.d"

. "$user_session_lib_dir/xkb_ctrl_esc_to_super.sh"

xkb_ctrl_esc_to_super

echo "Starting xmonad.."
exec ~/.xmonad/xmonad-i386-linux

