#!/bin/sh

set -euf

user_session_dir="$HOME/.Xsession.d"

session_files=$(run-parts --list $user_session_dir)
if [ -n "$session_files" ]; then
  for f in $session_files; do
    . $f
  done
fi

if [ "${include_xkb_ctrl_esc_to_super:-}" = "1" ]; then
    xkb_ctrl_esc_to_super
fi

# Haskell's `arch` from System.Info defines 32-bit architecture as i386, so
# should i.
uname_M="$(uname -m | sed -e 's/i686/i386/')"
# `tr` does not work for non-ascii chars, though is more compatible, than
# version with GNU sed's '\L' flag in s/// command (which works with unicode),
uname_S="$(uname -s | tr '[[:upper:]]' '[[:lower:]]')"
user_xmonad="$HOME/.xmonad/xmonad-$uname_M-$uname_S"
echo "Starting xmonad.."
exec $user_xmonad

